spring:
  application:
    name: gateway-api

server:
  port: 8000

movies-service:
  url: http://localhost:8081
events-service:
  url: http://localhost:8082
monolith:
  url: http://localhost:8080
gradual-migration: true
movies:
  migration-percent: "50"

management:
  endpoints:
    web:
      exposure:
        include: health
      base-path: /
      path-mapping:
        health: health
    health:
      show-details: always