apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJnaGNyLmlvIjogewogICAgICAiYXV0aCI6ICJZWEowTFhKbGMzQjFZbXhwWTJFNloyaHdYMkpCUjFOc1ZFbFlXREZyVlVsaGFHOUdPV3BPVjNCaWRWVnJja0oxUlRGUWFXcFNUZz09IgogICAgfQogIH0KfQ==
type: kubernetes.io/dockerconfigjson
